import streamlit as st

def run():
    st.header("Glossaire")
    st.write("")
    st.write("**Player Impact Estimate (PIE)**")
    st.write("Contribution globale d'un joueur au sein d'un match")
    st.write("Formule : (PTS + FGM + FTM - FGA - FTA + DREB + (.5 * OREB) + AST + STL + (.5 * BLK) - PF - TO) / (GmPTS + GmFGM + GmFTM - GmFGA - GmFTA + GmDREB + (.5 * GmOREB) + GmAST + GmSTL + (.5 * GmBLK) - GmPF - GmTO)")
    st.write("")
    st.write("")
    st.write("**Assists Ratio**")
    st.write("Le nombre moyen de passes décisives pour un joueur pour 100 possesions")
    st.write("Formule : (AST * 100) / (POSS)")
    st.write("")
    st.write("")
    st.write("**True Shooting %**")
    st.write("Un pourcentage au tir qui pondère la valeur d'un 3 points et d'un lancer-franc en plus d'un tir à 2 points")
    st.write("Formule : Points/ [2*(Field Goals Attempted+0.44*Free Throws Attempted)]")
    st.write("")
    st.write("")
    st.write("**Defensive Diff %**")
    st.write("La différence entre la pourcentage normal des attaquants et leur pourcentage lorsque que le joueur défend dessus. Un différentiel négatif indique donc la capacité d'un joueur à faire baisser le pourcentage d'un attaquant")
    st.write("Formule : oppFG% - oppDFG%")
    st.write("")
    st.write("")
    st.write("**Adjusted Rebound Chance %**")
    st.write("Le pourcentage de rebonds captés quand le joueur a une opportunité de rebond. Cet indicateur est ajusté en excluant des opportunités de rebound les rebonds qui sont déviés par le joueur à un coéquipier, qui ne sont pas comptabilisés comme un rebond")
    st.write("Formule : (REB)/(REB Chances - Deferred REB Chances)")
